[package]
name = "omelette"
version = "0.1.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]

[dependencies]
diesel = { version = "1.3.3", features = ["sqlite"] }
lazy_static = "1.1.0"
ncurses = "5.94.0"
rand = "0.5.5"
regex = "1.0.5"
