[package]
name = "gen-words"
version = "0.1.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"
serde = "1.0.75"
serde_derive = "1.0.75"
serde_json = "1.0.26"
regex = "1.0.4"