[package]
name = "gen-words"
version = "0.1.0"
authors = ["rookie1024 <rookie1286@gmail.com>"]

[dependencies]
dotenv = "0.13.0"
diesel = { version = "1.3.3", features = ["sqlite"] }
lazy_static = "1.1.0"
regex = "1.0.4"